export const SECTION_NERF_PNEUMOGASTRIQUE = 'SECTION_NERF_PNEUMOGASTRIQUE';
export const SECTION_NERF_PNEUMOGASTRIQUE_SYMPATIQUE = 'SECTION_NERF_PNEUMOGASTRIQUE_SYMPATIQUE';
export const SECTION_ERASE_ALL = 'SECTION_ERASE_ALL';
