export const STIMULATION_NERF_PNEUMOGASTRIQUE = 'STIMULATION_NERF_PNEUMOGASTRIQUE';
export const STIMULATION_NERF_SYMPATIQUE = 'STIMULATION_NERF_SYMPATIQUE';
export const STIMULATION_ERASE_ALL = 'STIMULATION_ERASE_ALL';
